### PR TITLE
[WIP] Adds JSONAPIAdapter format

### LINKED ISSUE #15: JSON API support
Since Ember Data is going JSON API by default, this might be necessary for this app to stay useful.

### PR DESCRIPTION
**Pull request by locks**
Fixes #15.

- [x] Update dependencies
- [x] Update `const`+destructuring idiom
- [x] Update computed properies and observers
- [x] Update template idioms (`each`, `bind-attr´)
- [x] Componentize the application
- [x] Select deprecation
- [x] Actually add JSONAPIAdapter
- [ ] Clean up

### CODE REVIEW

**Comment by andycrum** [comment]
Awesome! Thanks @locks. I was going to try to tackle this soon.. looking forward to watching your progress ;) Let me know if I can help in any way.

**Comment by locks** [comment]
Do you mind if I extract some parts of the interface into components?
Might make it easier to modify.

Will do! I'll try to get someone in the ED team to pitch in, I'm still green on the new format.

**Comment by andycrum** [comment]
Components would be great! Been hoping to clean up the code here at some point (when I can find time...)

**Comment by locks** [comment]
@andycrum I apologise for the flood of changes. If you want me to break it up to make it easier for you let me know.
Getting there! :P

**Pull request merged**
